name: Use API Key Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Use the API key securely in your project
      - name: Use API Key
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Running a task with the API Key..."
          curl -H "Authorization: Bearer $API_KEY" https://api.example.com/resource
